// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFjECtzerahDoJZF4DiuGHtb4_Rhvfbws',
    appId: '1:917258654265:web:205347e0a427b1aeeb33e8',
    messagingSenderId: '917258654265',
    projectId: 'studybookflutter',
    authDomain: 'studybookflutter.firebaseapp.com',
    storageBucket: 'studybookflutter.appspot.com',
    measurementId: 'G-SFPMJ1TRTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa7jHUds4yG86rxty62NI3O3pZTQJjfIU',
    appId: '1:917258654265:android:72dcc6c3957c9f63eb33e8',
    messagingSenderId: '917258654265',
    projectId: 'studybookflutter',
    storageBucket: 'studybookflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjH7nmCp8iYHq9xXGSaR43gO8LDNEzVPk',
    appId: '1:917258654265:ios:d77377bd539ec42eeb33e8',
    messagingSenderId: '917258654265',
    projectId: 'studybookflutter',
    storageBucket: 'studybookflutter.appspot.com',
    androidClientId: '917258654265-46ul2s02husriccaorggrr62q631phrc.apps.googleusercontent.com',
    iosClientId: '917258654265-9q445uaqeagvagsisanj9sgakdto18dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjH7nmCp8iYHq9xXGSaR43gO8LDNEzVPk',
    appId: '1:917258654265:ios:d77377bd539ec42eeb33e8',
    messagingSenderId: '917258654265',
    projectId: 'studybookflutter',
    storageBucket: 'studybookflutter.appspot.com',
    androidClientId: '917258654265-46ul2s02husriccaorggrr62q631phrc.apps.googleusercontent.com',
    iosClientId: '917258654265-9q445uaqeagvagsisanj9sgakdto18dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviebook',
  );
}
